ARG grafana_image=grafana
ARG grafana_version=13.0.3@sha256:1a345428a36270f5fb9add69fea71450a5843c15266c99359d6d380470ab19c9

FROM grafana/${grafana_image}:${grafana_version}

ARG backendUrl
ARG basicAuthUser
ARG basicAuthPassword

# Make it as simple as possible to access the grafana instance for development purposes
# Do NOT enable these settings in a public facing / production grafana instance
ENV GF_AUTH_ANONYMOUS_ORG_ROLE="Admin"
ENV GF_AUTH_ANONYMOUS_ENABLED="true"
ENV GF_AUTH_BASIC_ENABLED="false"
# Set development mode so plugins can be loaded without the need to sign
ENV GF_DEFAULT_APP_MODE="development"


USER root

# Prevent Grafana from replacing and deleting the bind-mounted development plugin.
RUN sed -i '/^\[feature_toggles\]$/a preinstallAutoUpdate = false' /etc/grafana/grafana.ini

# This ensures that the basicAuthUser value is a string and not a number
# which would make the requests to the backend fail
COPY ./samples/provisioning-remote/plugins/app.yaml  /etc/grafana/provisioning/plugins
